[tool.poetry]
name = "WakAPI"
version = "0.1"
description = "WakaTime api client"
authors = ["Tomoya Ogawa <t.ogawa@ogatomo.net>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ogatomo21/wakapi"